Bidirectional Dollar Cost Average Bridge
AztecProtocol/aztec-connect-bridges pull request #135
Opened 2022-06-27 10:57 UTC by LHerskind

# Description

A **very early draft reference implementation** of a DeFi bridge that let users open a DCA position, striving to swap x A to y B over z time. Time is defined in `ticks` to allow aggregation of multiple DCA positions. 

The bridge allows both positions going A -> B and B -> A, giving us the ability to match these directly before needing to sell tokens to external parties. e.g., if Alice want to swap A -> B and bob B -> A, for a given tick, one of them can be filled using the others DCA.

To handle the excess (stuff we cannot match between DCAs directly), we can use an external party, who might buy without slippage using some oracle price. And if no-one is interested in that, the excess should be traded directly through a dex etc.

# Checklist:

- [ ] I have reviewed my diff in github, line by line.
- [ ] Every change is related to the PR description.
- [ ] There are no unexpected formatting changes, or superfluous debug logs.
- [ ] The branch has been rebased against the head of its merge target.
- [ ] I'm happy for the PR to be merged at the reviewers next convenience.

2022-07-25 13:17 UTC, benesjan requested changes
Currently only pointed out naming issues. Can you please finish full NatSpec before I review it again? The bridge is complex and I spend too much time decoding what the params and global vars mean.

2022-08-08 13:02 UTC, LHerskind commented on src/bridges/dca/BiDCABridge.sol
> +    function pokeTicks(uint256 _startTick, uint256 _ticks) public {
`pokeNextTicks` are calling this function

2022-08-12 11:09 UTC, benesjan commented on src/bridges/dca/BiDCABridge.sol
> + */
Can you please describe here how the bridge internally works? How the ticks are indexed by time, how does rebalancing work etc.

2022-08-23 09:28 UTC, benesjan reviewed
Changes look good to me. The comments clarified it a lot and the incentive is a good idea.

2022-08-23 09:28 UTC, benesjan commented on src/bridges/dca/BiDCABridge.sol
> + * (or infer price from prior price and current price). The excess from this internal matching is then sold off (of as much as possible).
"(of as much as possible)" sounds a bit weird. Should it be "(for as much as possible)"?

2022-08-23 09:28 UTC, benesjan commented on src/bridges/dca/UniswapDCABridge.sol
> + * @dev The `MAX_AGE` of a price feed, means that a abandoned price-feed will brick the bridge.
```suggestion
 * @dev The `MAX_AGE` of a price feed, means that an abandoned price-feed will brick the bridge.
```

2022-08-23 09:28 UTC, benesjan commented on src/specs/dca/readme.md
> +To incentivise searchers on L1 to finalise the transactions, a fee of 10 basis points of the swapped assets are paid to the initiator of the transaction (`tx.origin` instead of `msg.sender` as the ro
Fee is specified in constructor so should be saying that instead of fixed 10 basis point fee.

2022-09-22 08:42 UTC, merged